import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * mudei MetaData para um arquivo separado para poder usar 'use client' no layout.tsx 
 * para poder usar themeProvader
 */